### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by lp35** [khuttun/PolyM#6]
Hi,

First thank you for the hard work. Very interesting to see clean code with pimpl.

I have few suggestions for your library though. Each of them deserve a PR I can make.

1.  https://github.com/khuttun/PolyM/blob/f97db66f4c63e8af585af1eeb65acbf10b6ba8f5/Queue.hpp#L30-L38
Why not returning an empty pointer instead of forging a new message?
This could allow returning nullptr thus avoiding pushing then poping from the queue here: https://github.com/khuttun/PolyM/blob/f97db66f4c63e8af585af1eeb65acbf10b6ba8f5/Queue.cpp#L44-L50

2. I think a try_get could be really useful: 
``` 
/**
    * Get message from the head of the queue. Returns an empty pointer if no 
    * message is available.
    */
    std::unique_ptr<Msg> try_get(); 
```

3. https://github.com/khuttun/PolyM/blob/f97db66f4c63e8af585af1eeb65acbf10b6ba8f5/Queue.cpp#L57-L59
I find this a bit too overkill to recreate a new message queue. But I think there are not other design for this?

Thank you again for this wonderful piece of code!
BR

**Comment by khuttun** [comment]
Hi! Thanks for the feedback. All of the comments are good:

1. I agree, MSG_TIMEOUT is unnecessary and could be replaced with nullptr. This changes the interface, though. But if you make a PR and we put it to master we could make a "v2 release" of PolyM that contains your improvements and release notes that state that the interface is not compatible with the "v1 release" (current version).

2. I agree, `tryGet` would be a useful addition.

3. Yes, there's some unnecessary overhead with creating a full `Queue` object for handling the response: the response map and the associated mutex are not needed, and instead of `std::queue` we would need just a single `std::unique_ptr<Msg>`. Maybe an auxiliary data structure that contains only the bare minimum needed could be added. But there would be a need to add very similar "get" and "put" functions for the response handling as `Queue::get` and `Queue::put` are.

Pull requests are most welcome!

**Comment by khuttun** [comment]
I think all of the suggestions have now been addressed and this can be closed
